name: CI
on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: mylab-vm
    container:
      image: node:14.16

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
