name: 'GCP gcloud'

on:
  workflow_dispatch:
    inputs:
      update:
        type: boolean
        default: true
jobs:
  google:
    name: 'gcloud-google'

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/758849761540/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'terraform-sa@mevijay-dev.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 418.0.0'
        install_components: 'alpha,kubectl,gsutil'   
    - name: docker login
      run: |
        gcloud auth configure-docker \
        us-central1-docker.pkg.dev
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Image tag
      id: tag
      run: |
        echo "tag=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: docker
        push: true
        tags: us-central1-docker.pkg.dev/mevijay-dev/forddb/myimage:${{ steps.tag.outputs.tag }}
    - id: 'deploy'
      if: ${{ github.event.inputs.update == 'false' }}
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        metadata: cloudrun/service.yaml
    - name: update tag
      run: |
        sed -i 's/latest/${{ steps.tag.outputs.tag }}/g' cloudrun/service.yaml
    - name: update container
      run: |
        gcloud run services replace --region us-central1 cloudrun/service.yaml
    - name: cloudrun url
      id: appurl
      run: |
        echo "URL=$(gcloud run services list --platform managed | awk 'NR==2 {print $4}')" >> $GITHUB_OUTPUT
    - run: echo "::notice title=${{ steps.appurl.outputs.URL }}"
 
