on: workflow_dispatch
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
